# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppChuckViewCode' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppChuckViewCode

  target 'AppChuckViewCodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Alamofire'
pod 'OHHTTPStubs/Swift' 

end
